### PR TITLE
feat(CI): publish rock with branch tag on manual dispatch

### PR DESCRIPTION
**Pull request by Guillaumebeuzeboc**
Publish the rock from a branch with the branch tag when ROCK is is manually triggered.

### CODE REVIEW

**Comment by artivis** [comment]
Should we propose this feature upstream?

**Comment by Guillaumebeuzeboc** [comment]
> When manually launching, you can pick the branch on which to run this?

Yes,
image

**Comment by Guillaumebeuzeboc** [comment]
> Should we propose this feature upstream?

We can, should we open an issue or PR directly or ask in a private channel?

**Comment by artivis** [comment]
> We can, should we open an issue or PR directly or ask in a private channel?

I'd say issue or dm :+1:

**Comment by Guillaumebeuzeboc** [comment]
> > We can, should we open an issue or PR directly or ask in a private channel?
> 
> I'd say issue or dm 👍

Done here: https://github.com/canonical/observability/issues/147

**Pull request merged**
